


#----------------front routes-------------------------
home:
  path: /
  controller: App\Controller\HomeController::index

front_view:
  path: /view/{id}-{name}
  controller: App\Controller\AccomodationController::view

front_search:
  path: /search/{search}
  controller: App\Controller\AccomodationController::search


#----------------User routes-------------------------
admin_home_page :
  path : /user
  controller: App\Controller\AdminController::index


user_profile :
  path : /user/profile
  controller: App\Controller\AdminController::editProfile

user_reviews :
  path: /user/reviews
  controller: App\Controller\AdminController::editReviews

reviews_update :
  path : /user/reviews/upd
  controller: App\Controller\AdminController::updateReviews

reviews_delete :
  path : /user/reviews/del/{id}
  controller: App\Controller\AdminController::deleteReviews

user_favorites :
  path : /user/favorites
  controller: App\Controller\AdminController::editFavorites

user_reservations :
  path : /user/reservations
  controller: App\Controller\AdminController::editReservations

user_bill :
  path : /user/bill
  controller: App\Controller\AdminController::editBill

user_accomodation :
  path : /user/accomodation
  controller: App\Controller\AdminController::editAccomodation

add_accomodation :
  path : /user/accomodation/add
  controller : App\Controller\AdminController::addAccomodation

#----------------Owner routes-------------------------
owner_accomodation :
  path : /owner/accomodation
  controller: App\Controller\OwnerController::editAccomodation

owner_availability :
  path : /owner/availability
  controller: App\Controller\OwnerController::editAvailability

owner_booking :
  path : /owner/booking
  controller: App\Controller\OwnerController::editBooking


#----------------Utilities routes-------------------------
app_logout:
  path: /logout

#----------------Api routes-------------------------------
api_accomodations:
  path: /api/accomodations
  controller: App\Controller\Api\AccomodationController::index
